version: '3.9'
services:
  api:
    build: .
    ports: ["5000:5000"]
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_ENV=development
      - PORT=5000
    volumes:
      - .:/app